### ISSUE TITLE
Workflow to test pods

### ISSUE THREAD

**Issue by offlinehacker** [bipio-server/bipio#53]
Currently there's no description how to manually or automatically test pods, without installing them to bip-io server. What's the best way to test them?

**Comment by mjpearson** [comment]
Hi, we don't have any pod tests available in the public repo's, but here's the general gist of it :  

https://gist.github.com/mjpearson/9aceb70812ffc162e80c

Because pods require certain dependencies from the server (such as data access), its generally easier to enable the pod in the server and test actions via it's API's
